# yaml-language-server: $schema=../../json_schemas/main/Agent.json
---
apiVersion: flock/v1
kind: Agent
namespace: default
metadata:
  name: my-agent
  description: A Q&A agent for internal projects
  labels:
    app: my_app
spec:
  vendor: zero-shot-react-description
  options:
    verbose: true
  dependencies:
    - kind: LLMChat
      name: openai-gpt-4
      namespace: default
  tools:
    - kind: LoadTool
      name: google-search-gpt-4
      namespace: default
