# yaml-language-server: $schema=../../json_schemas/main/Agent.json
---
apiVersion: flock/v1
kind: Agent
namespace: default
metadata:
  name: task-delegation-agent
  description: An autonomous agent
  labels:
    app: my_app
spec:
  vendor: zero-shot-react-description
  options:
    verbose: true
    agent_kwargs:
      prefix: |
        You are an AI who performs one task based on the following objective: {objective}. Take into account these previously completed tasks: {context}.
      suffix: |
        Question: {task}
        {agent_scratchpad}
      input_variables: ["objective", "task", "context", "agent_scratchpad"]
  dependencies:
    - kind: LLMChat
      name: openai-gpt-4
      namespace: default
  tools:
    - kind: LLMTool
      name: todo-list-tool
      namespace: default
    - kind: LoadTool
      name: google-search-gpt-4
      namespace: default
