# yaml-language-server: $schema=../../json_schemas/main/AgentSchema.json
---
apiVersion: flock/v1
kind: Agent
namespace: default
metadata:
  name: advanced-exp-agent
  description: an agent with set of tools
  labels:
    app: my_app
spec:
  vendor: conversational-react-description
  options:
    verbose: true
  dependencies:
    - kind: LLMChat
      name: my-openai-llm
      namespace: default
  tools:
    # - kind: VectorStoreQATool
    #   name: langchain-docs
    #   namespace: default
    - kind: LoadTool
      name: my-google-search
      namespace: default
    - kind: LoadTool
      name: my-wolfram-alpha
      namespace: default
