# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.base_dependency import BaseDependency
from server.models.base_tool_dependency import BaseToolDependency


class BaseSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BaseSpec - a model defined in OpenAPI

        options: The options of this BaseSpec [Optional].
        vendor: The vendor of this BaseSpec.
        dependencies: The dependencies of this BaseSpec [Optional].
        tools: The tools of this BaseSpec [Optional].
    """

    options: Optional[Dict[str, Any]] = Field(alias="options", default=None)
    vendor: str = Field(alias="vendor")
    dependencies: Optional[List[BaseDependency]] = Field(alias="dependencies", default=None)
    tools: Optional[List[BaseToolDependency]] = Field(alias="tools", default=None)

BaseSpec.update_forward_refs()
