# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.embedding_vendor import EmbeddingVendor


class EmbeddingSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EmbeddingSpec - a model defined in OpenAPI

        options: The options of this EmbeddingSpec [Optional].
        vendor: The vendor of this EmbeddingSpec.
    """

    options: Optional[Dict[str, Any]] = Field(alias="options", default=None)
    vendor: EmbeddingVendor = Field(alias="vendor")

EmbeddingSpec.update_forward_refs()
