# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.llm_vendor import LLMVendor


class LLMSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LLMSpec - a model defined in OpenAPI

        options: The options of this LLMSpec [Optional].
        vendor: The vendor of this LLMSpec.
    """

    options: Optional[Dict[str, Any]] = Field(alias="options", default=None)
    vendor: LLMVendor = Field(alias="vendor")

LLMSpec.update_forward_refs()
