# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.code7 import Code7
from server.models.resource_deleted_data import ResourceDeletedData
from server.models.status import Status


class ResourceDeleted(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceDeleted - a model defined in OpenAPI

        status: The status of this ResourceDeleted [Optional].
        message: The message of this ResourceDeleted [Optional].
        code: The code of this ResourceDeleted [Optional].
        data: The data of this ResourceDeleted [Optional].
    """

    status: Optional[Status] = Field(alias="status", default=None)
    message: Optional[str] = Field(alias="message", default=None)
    code: Optional[Code7] = Field(alias="code", default=None)
    data: Optional[ResourceDeletedData] = Field(alias="data", default=None)

ResourceDeleted.update_forward_refs()
