# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.splitter_vendor import SplitterVendor


class SplitterSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SplitterSpec - a model defined in OpenAPI

        options: The options of this SplitterSpec [Optional].
        vendor: The vendor of this SplitterSpec.
    """

    options: Optional[Dict[str, Any]] = Field(alias="options", default=None)
    vendor: SplitterVendor = Field(alias="vendor")

SplitterSpec.update_forward_refs()
