# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class VectorStoreSchemaSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VectorStoreSchemaSpec - a model defined in OpenAPI

        options: The options of this VectorStoreSchemaSpec [Optional].
        vendor: The vendor of this VectorStoreSchemaSpec.
        dependencies: The dependencies of this VectorStoreSchemaSpec.
    """

    options: Optional[Dict[str, Any]] = Field(alias="options", default=None)
    vendor: str = Field(alias="vendor")
    dependencies: List[object] = Field(alias="dependencies")

VectorStoreSchemaSpec.update_forward_refs()
