# yaml-language-server: $schema=../json_schemas/JobSchema.json
---
apiVersion: flock/v1
kind: FlockJob
namespace: default
category: job
metadata:
  name: web-scraper
  description: web scraper - scrape data from the web
  labels:
    app: my_app
spec:
  container:
    image_pull_policy: IfNotPresent
    image: flock-webscraper
    env:
      - name: SCRAPER_NAME
        value: "test_spider"
      - name: SCRAPER_START_URLS
        value: "http://books.toscrape.com/catalogue/category/books/romance_8/index.html"
      - name: RULE_SCRAPER_ALLOWED_DOMAINS
        value: "books.toscrape.com"
      - name: RULE_SCRAPER_ALLOW
        value: "/catalogue/category/books/romance_8 /catalogue/category/books/philosophy_7"
      - name: RULE_SCRAPER_DENY_EXTENSIONS
        value: ""
      - name: SCRAPER_OUTPUT_DIR
        value: "/app/spider_output"
      - name: SCRAPER_FEED_EXPORT_BATCH_ITEM_COUNT
        value: "10"
  targetResource:
    kind: WebScraper
    name: my-embedding-data-loader
    namespace: default
    labels:
      app: my_app
