# yaml-language-server: $schema=../../json_schemas/main/VectorStoreQAToolSchema.json
---
apiVersion: flock/v1
kind: VectorStoreQATool
namespace: default
metadata:
  name: langchain-docs
  description: retrieve docs from langchain docs vector store
  labels:
    app: my_app
spec:
  vendor: RetrievalQAWithSourcesChain
  options:
    chain_type: stuff
    reduce_k_below_max_tokens: true
  dependencies:
    - kind: VectorStore
      name: documentation_vectorstore
      namespace: default
    - kind: LLMChat
      name: my-openai-llm
      namespace: default
