# Build Stage
FROM flock-base:latest AS build


# Expose the port the app runs on
EXPOSE 8000

# Start the application
ENTRYPOINT [ "poetry", "run", "python", "flock_agent/main.py" ]
CMD [ "run-agent" ]
