##### Flock Base Stage #####
FROM flock-python-base as flock-base-stage

COPY libs $PYSETUP_PATH/libs
COPY services $PYSETUP_PATH/services

##### Flock Base Agent #####
FROM flock-base-stage as agent-base-stage

ENV FASTAPI_ENV=production
WORKDIR $PYSETUP_PATH/flock_agent

RUN poetry install --only main

##### Flock Base EmbeddingsLoader #####
FROM flock-base-stage as embeddings-loader-base-stage

ENV FASTAPI_ENV=production
WORKDIR $PYSETUP_PATH/flock_embeddings_loader

RUN poetry install --only main


######### Final Stages #########

##### Flock Agent Stage #####
FROM python:3.9.15-slim as agent-stage

ENV PYSETUP_PATH="/opt/pysetup"

COPY --from=agent-base-stage $PYSETUP_PATH/flock_schemas/flock_schemas $PYSETUP_PATH/flock_schemas/flock_schemas
COPY --from=agent-base-stage $PYSETUP_PATH/flock_resource_store/flock_resource_store $PYSETUP_PATH/flock_resource_store/flock_resource_store
COPY --from=agent-base-stage $PYSETUP_PATH/flock_common/flock_common $PYSETUP_PATH/flock_common/flock_common

COPY --from=agent-base-stage $PYSETUP_PATH/flock_agent/.venv $PYSETUP_PATH/flock_agent/.venv
COPY ./flock_agent/flock_agent  $PYSETUP_PATH/flock_agent/flock_agent

WORKDIR $PYSETUP_PATH/flock_agent

ENV VIRTUAL_ENV="${PYSETUP_PATH}/flock_agent/.venv"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

EXPOSE 8000
ENTRYPOINT ["python", "flock_agent/main.py" ]
CMD [ "run-agent" ]


##### Flock EmbeddingsLoader Stage #####
FROM python:3.9.15-slim as embeddings-loader-stage

ENV PYSETUP_PATH="/opt/pysetup"

COPY --from=embeddings-loader-base-stage $PYSETUP_PATH/flock_schemas/flock_schemas $PYSETUP_PATH/flock_schemas/flock_schemas
COPY --from=embeddings-loader-base-stage $PYSETUP_PATH/flock_resource_store/flock_resource_store $PYSETUP_PATH/flock_resource_store/flock_resource_store
COPY --from=embeddings-loader-base-stage $PYSETUP_PATH/flock_common/flock_common $PYSETUP_PATH/flock_common/flock_common

COPY --from=embeddings-loader-base-stage $PYSETUP_PATH/flock_embeddings_loader/.venv $PYSETUP_PATH/flock_embeddings_loader/.venv
COPY ./flock_embeddings_loader/flock_embeddings_loader  $PYSETUP_PATH/flock_embeddings_loader/flock_embeddings_loader

WORKDIR $PYSETUP_PATH/flock_embeddings_loader


ENV VIRTUAL_ENV="${PYSETUP_PATH}/flock_embeddings_loader/.venv"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

EXPOSE 8000
ENTRYPOINT ["python", "flock_embeddings_loader/main.py" ]
CMD [ "run-job" ]
