##### Flock Base Agent #####
FROM flock-python-base as agent-base-stage

ENV FASTAPI_ENV=production

COPY ./libs/flock_common $PYSETUP_PATH/libs/flock_common
COPY ./libs/flock_resources $PYSETUP_PATH/libs/flock_resources
COPY ./libs/flock_task_management_store $PYSETUP_PATH/libs/flock_task_management_store
COPY ./libs/flock_schemas $PYSETUP_PATH/libs/flock_schemas
COPY ./libs/flock_resource_store $PYSETUP_PATH/libs/flock_resource_store

COPY ./services/flock_agent $PYSETUP_PATH/services/flock_agent

WORKDIR $PYSETUP_PATH/services/flock_agent

# RUN poetry install --only main
RUN python -m venv .venv
RUN .venv/bin/pip install --use-pep517 . 


##### Flock Agent Stage #####
FROM python:3.10.10-slim as agent-stage

ENV PYSETUP_PATH="/opt/pysetup"

COPY --from=agent-base-stage $PYSETUP_PATH/libs $PYSETUP_PATH/libs

COPY --from=agent-base-stage $PYSETUP_PATH/services/flock_agent/.venv $PYSETUP_PATH/services/flock_agent/.venv
COPY --from=agent-base-stage $PYSETUP_PATH/services/flock_agent/flock_agent $PYSETUP_PATH/services/flock_agent/flock_agent

WORKDIR $PYSETUP_PATH/services/flock_agent

ENV VIRTUAL_ENV="${PYSETUP_PATH}/services/flock_agent/.venv"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

EXPOSE 80
ENTRYPOINT ["python", "flock_agent/main.py" ]
CMD [ "run-agent" ]

