# yaml-language-server: $schema=../../json_schemas/main/CustomSchema.json
---
apiVersion: flock/v1
kind: BabyAGI
namespace: default
metadata:
  name: my-baby-agi
  description: A baby AGI
  labels:
    app: my_app
spec:
  vendor: BabyAGI
  options:
    verbose: false
    max_iterations: 3
  dependencies:
    - kind: LLMChat
      name: my-openai-llm # my-openai-gpt4all-llm # my-openai-llm
      namespace: default
    - kind: Embedding
      name: my-openai-embedding
      namespace: default
    - kind: Agent
      name: my-baby-agi-agent
      namespace: default
