# apiVersion: v1
# kind: Service
# metadata:
#   name: flock-mongo-service
# spec:
#   selector:
#     app: flock-mongo
#   ports:
#     - protocol: TCP
#       port: 27017
#       targetPort: 27017
# ---
apiVersion: v1
kind: Service
metadata:
  name: flock-resource-store
spec:
  type: NodePort
  selector:
    app: flock-resource-store
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30200
