# yaml-language-server: $schema=../../json_schemas/main/LoadToolSchema.json
---
apiVersion: flock/v1
kind: LoadTool
namespace: default
metadata:
  name: my-google-search
  description: Reliable source for current events, facts, and extensive research beyond 2021.
  labels:
    app: my_app
spec:
  vendor: serpapi
  dependencies:
    - kind: LLMChat
      name: my-openai-llm
      namespace: default
