# yaml-language-server: $schema=../../json_schemas/main/LoadToolSchema.json
---
apiVersion: flock/v1
kind: LoadTool
namespace: default
metadata:
  name: my-google-search
  description: Useful for answering questions about current events, and for further research on the internet
  labels:
    app: my_app
spec:
  vendor: serpapi
  dependencies:
    - kind: LLMChat
      name: my-openai-llm
      namespace: default
