# yaml-language-server: $schema=../../json_schemas/main/VectorStoreQATool.json
---
apiVersion: flock/v1
kind: VectorStoreQATool
namespace: default
metadata:
  name: finance-qa-tool
  description: Knowledge about Meta Reports First Quarter 2023 Results
  labels:
    app: my_app
spec:
  vendor: RetrievalQAWithSourcesChain # VectorDBQAWithSourcesChain
  options:
    chain_type: stuff
    reduce_k_below_max_tokens: true
    verbose: true
  dependencies:
    - kind: VectorStore
      name: meta_reports
      namespace: default
    - kind: LLMChat
      name: openai-gpt-3-5
      namespace: default
