# yaml-language-server: $schema=../../../json_schemas/main/VectorStoreQAToolSchema.json
---
apiVersion: flock/v1
kind: VectorStoreQATool
namespace: default
metadata:
  name: finance-qa-tool
  description: Knowledge about Meta Reports First Quarter 2023 Results
  labels:
    app: my_app
spec:
  vendor: RetrievalQAWithSourcesChain # VectorDBQAWithSourcesChain
  options:
    chain_type: stuff
    reduce_k_below_max_tokens: true
    verbose: true
  dependencies:
    - kind: VectorStore
      name: documentation_vectorstore
      namespace: default
    - kind: LLMChat
      name: my-openai-llm
      namespace: default
