# yaml-language-server: $schema=../../json_schemas/main/DeploymentKindConfig.json
---
apiVersion: flock/v1
kind: DeploymentKindConfig
kind_target: Agent
metadata:
  name: agent_kind_config
  description: agent default global config
env:
  - name: RESOURCE_STORE_HOST
    value: "mongo"
  - name: RESOURCE_STORE_USERNAME
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: mongo-username
  - name: RESOURCE_STORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: mongo-password
  - name: FLOCK_AGENT_PORT
    value: "80"
  - name: FLOCK_AGENT_HOST
    value: "0.0.0.0"
  - name: QUEUE_HOST
    value: "flock-queue-rabbitmq-headless"
  - name: MANAGEMENT_STORE_HOST
    value: "mongo"
  - name: LOG_LEVEL
    value: "DEBUG"
