# yaml-language-server: $schema=../../json_schemas/main/DeploymentKindConfig.json
---
apiVersion: flock/v1
kind: DeploymentKindConfig
kind_target: WebScraper
metadata:
  name: webscraper_kind_config
  description: webscraper default global config
env:
  - name: SCRAPER_OUTPUT_DIR
    value: /flock-data/embeddings/pre_processed
  - name: SCRAPER_NAME
    value: "books"
  - name: SCRAPER_START_URLS
    value: "http://books.toscrape.com/catalogue/category/books/romance_8/index.html"
  - name: RULE_SCRAPER_ALLOWED_DOMAINS
    value: "books.toscrape.com"
  - name: RULE_SCRAPER_ALLOW
    value: "/catalogue/category/books/romance_8 /catalogue/category/books/philosophy_7"
  - name: RULE_SCRAPER_DENY_EXTENSIONS
    value: ""
  - name: SCRAPER_FEED_EXPORT_BATCH_ITEM_COUNT
    value: "10"
