# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.kind import Kind


class BaseDependency(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BaseDependency - a model defined in OpenAPI

        labels: The labels of this BaseDependency [Optional].
        name: The name of this BaseDependency.
        kind: The kind of this BaseDependency.
        namespace: The namespace of this BaseDependency [Optional].
    """

    labels: Optional[Dict[str, str]] = Field(alias="labels", default=None)
    name: str = Field(alias="name")
    kind: Kind = Field(alias="kind")
    namespace: Optional[str] = Field(alias="namespace", default=None)

    @validator("namespace")
    def namespace_max_length(cls, value):
        assert len(value) <= 63
        return value

BaseDependency.update_forward_refs()
