# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.load_tool_vendor import LoadToolVendor


class LoadToolSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LoadToolSpec - a model defined in OpenAPI

        options: The options of this LoadToolSpec [Optional].
        vendor: The vendor of this LoadToolSpec.
        dependencies: The dependencies of this LoadToolSpec.
    """

    options: Optional[Dict[str, Any]] = Field(alias="options", default=None)
    vendor: LoadToolVendor = Field(alias="vendor")
    dependencies: List[object] = Field(alias="dependencies")

LoadToolSpec.update_forward_refs()
