# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.prompt_template_vendor import PromptTemplateVendor


class PromptTemplateSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PromptTemplateSpec - a model defined in OpenAPI

        options: The options of this PromptTemplateSpec [Optional].
        vendor: The vendor of this PromptTemplateSpec.
    """

    options: Optional[Dict[str, Any]] = Field(alias="options", default=None)
    vendor: PromptTemplateVendor = Field(alias="vendor")

PromptTemplateSpec.update_forward_refs()
