# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.code import Code
from server.models.resource_details import ResourceDetails
from server.models.status import Status


class ResourcesFetched(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourcesFetched - a model defined in OpenAPI

        status: The status of this ResourcesFetched [Optional].
        message: The message of this ResourcesFetched [Optional].
        code: The code of this ResourcesFetched [Optional].
        data: The data of this ResourcesFetched [Optional].
    """

    status: Optional[Status] = Field(alias="status", default=None)
    message: Optional[str] = Field(alias="message", default=None)
    code: Optional[Code] = Field(alias="code", default=None)
    data: Optional[ResourceDetails] = Field(alias="data", default=None)

ResourcesFetched.update_forward_refs()
