# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.code3 import Code3
from server.models.resource_data import ResourceData
from server.models.status import Status


class ResourceCreated(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceCreated - a model defined in OpenAPI

        status: The status of this ResourceCreated [Optional].
        code: The code of this ResourceCreated [Optional].
        data: The data of this ResourceCreated [Optional].
        message: The message of this ResourceCreated [Optional].
    """

    status: Optional[Status] = Field(alias="status", default=None)
    code: Optional[Code3] = Field(alias="code", default=None)
    data: Optional[ResourceData] = Field(alias="data", default=None)
    message: Optional[str] = Field(alias="message", default=None)

ResourceCreated.update_forward_refs()
