# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.status_code import Code
from server.models.resource_data import ResourceData
from server.models.status import Status


class ResourceFetched(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceFetched - a model defined in OpenAPI

        status: The status of this ResourceFetched [Optional].
        message: The message of this ResourceFetched [Optional].
        code: The code of this ResourceFetched [Optional].
        data: The data of this ResourceFetched [Optional].
    """

    status: Optional[Status] = Field(alias="status", default=None)
    message: Optional[str] = Field(alias="message", default=None)
    code: Optional[Code] = Field(alias="code", default=None)
    data: Optional[ResourceData] = Field(alias="data", default=None)


ResourceFetched.update_forward_refs()
