# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from server.models.code4 import Code4
from server.models.status import Status
from server.schemas.resource_data import ResourceData


class ResourceAccepted(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceAccepted - a model defined in OpenAPI

        status: The status of this ResourceAccepted [Optional].
        code: The code of this ResourceAccepted [Optional].
        data: The data of this ResourceAccepted [Optional].
        message: The message of this ResourceAccepted [Optional].
    """

    status: Optional[Status] = Field(alias="status", default=None)
    code: Optional[Code4] = Field(alias="code", default=None)
    data: Optional[ResourceData] = Field(alias="data", default=None)
    message: Optional[str] = Field(alias="message", default=None)


ResourceAccepted.update_forward_refs()
