# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from server.models.vector_store_qa_tool_vendor import VectorStoreQAToolVendor


class VectorStoreQAToolSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VectorStoreQAToolSpec - a model defined in OpenAPI

        options: The options of this VectorStoreQAToolSpec [Optional].
        vendor: The vendor of this VectorStoreQAToolSpec.
        dependencies: The dependencies of this VectorStoreQAToolSpec.
    """

    options: Optional[Dict[str, Any]] = Field(alias="options", default=None)
    vendor: VectorStoreQAToolVendor = Field(alias="vendor")
    dependencies: List[object] = Field(alias="dependencies")

VectorStoreQAToolSpec.update_forward_refs()
