apiVersion: v1
kind: Service
metadata:
  name: flock-resources-server
spec:
  type: NodePort
  selector:
    app: flock-resources-server
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
      nodePort: 30207
