apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployer-role
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources: ["deployments", "services", "jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
