apiVersion: v1
kind: Service
metadata:
  name: flock-deployer
spec:
  type: NodePort
  selector:
    app: flock-deployer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30205
