# coding: utf-8

"""
    Flock

    Flock Orchestrator

    The version of the OpenAPI document: 0.0.1
    Contact: adam.yodinsky@gmail.com
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from server.api.flock_api import router as DefaultApiRouter
from server.api.flock_api import router as FlockApiRouter

app = FastAPI(
    title="Flock",
    description="Flock Orchestrator",
    version="0.0.1",
)

app.include_router(DefaultApiRouter)
app.include_router(FlockApiRouter)
