# yaml-language-server: $schema=../../json_schemas/main/AgentSchema.json
---
apiVersion: flock/v1
kind: Agent
namespace: default
metadata:
  name: flock-conversational-agent
  description: A Q&A agent for internal projects
  labels:
    app: my_app
spec:
  vendor: conversational-react-description
  options:
    verbose: true
  dependencies:
    - kind: LLMChat
      name: my-openai-llm
      namespace: default
  tools:
    - kind: VectorStoreQATool
      name: finance-qa-tool
      namespace: default
    - kind: LoadTool
      name: my-google-search
      namespace: default
