# Build Stage
FROM flock-base:latest AS build


# Set the working directory
WORKDIR /app/flock_agent

# Expose the port the app runs on
EXPOSE 8000

# Start the application
ENTRYPOINT [ "poetry", "run", "python", "flock_agent/main.py" ]
CMD [ "run-agent" ]

