# yaml-language-server: $schema=../../json_schemas/main/Agent.json
---
apiVersion: flock/v1
kind: Agent
namespace: default
metadata:
  name: advanced-agent
  description: an agent with set of tools
  labels:
    app: my_app
spec:
  vendor: conversational-react-description
  options:
    verbose: true
  dependencies:
    - kind: LLMChat
      name: my-openai-gpt4all-llm # my-openai-llm
      namespace: default
  tools:
    - kind: VectorStoreQATool
      name: finance-qa-tool
      namespace: default
    - kind: LoadTool
      name: my-google-search
      namespace: default
    - kind: LoadTool
      name: my-wolfram-alpha
      namespace: default
