# yaml-language-server: $schema=../../json_schemas/main/Agent.json
---
apiVersion: flock/v1
kind: Agent
namespace: default
metadata:
  name: advanced-agent
  description: an agent with set of tools
  labels:
    app: my_app
spec:
  vendor: conversational-react-description
  options:
    verbose: true
  dependencies:
    - kind: LLMChat
      name: gpt4all-llm-copycat
      namespace: default
  tools:
    - kind: VectorStoreQATool
      name: finance-qa-tool
      namespace: default
    - kind: LoadTool
      name: google-search-gpt-4
      namespace: default
    - kind: LoadTool
      name: wolfram-alpha
      namespace: default
