# yaml-language-server: $schema=../../json_schemas/main/Custom.json
---
apiVersion: flock/v1
kind: BabyAGI
namespace: default
metadata:
  name: my-baby-agi
  description: A baby AGI
  labels:
    app: my_app
spec:
  vendor: BabyAGI
  options:
    verbose: true
    max_iterations: 3
  dependencies:
    - kind: LLMChat
      name: openai-gpt-4
      namespace: default
    - kind: Embedding
      name: openai-embedding
      namespace: default
    - kind: Agent
      name: task-delegation-agent
      namespace: default
