apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  openai-token: c2stelRUNGZ1MWV0SllZcm9OdHdhWTBUM0JsYmtGSjA3d3pqNWNvRGN6aXQxVFhmS3dnCg==
  serpapi-token: YTM4MDM3ODI3NDZkYTA0OWJhY2FiMGQ2NmM3OTg3ZTE3NmRhOTI1YjE4YmZhMjQ1MzZjNWIyZjFhMjU5N2IyZgo=
  mongo-username: root
  mongo-password: password
