# yaml-language-server: $schema=../../json_schemas/main/DeploymentSchema.json
---
apiVersion: flock/v1
kind: FlockDeployment
namespace: default
category: deployment
metadata:
  name: my-agent-deployment
  description: A Q&A chat agent server
  labels:
    app: my_app
spec:
  container:
    image_pull_policy: IfNotPresent
    image: flock-agent
    ports:
      - name: http
        port: 80
        protocol: TCP
    env:
      - name: RESOURCE_STORE_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: mongo-username
      - name: RESOURCE_STORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: mongo-password
      - name: FLOCK_AGENT_PORT
        value: "8080"
      - name: FLOCK_AGENT_HOST
        value: "0.0.0.0"
      - name: RESOURCE_STORE_HOST
        value: "192.168.1.162"
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: openai-token
      - name: SERPAPI_API_KEY
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: serpapi-token
  targetResource:
    kind: Agent # this is an agent resource manifest reference that should be loaded to the Flock-Agent FastAPI app.
    name: my-agent
    namespace: default
    labels:
      app: my_app
    options: # this is a dict of options that will be passed to the Flock-Agent FastAPI app. deployer can use this to override the options in the target's manifest
      verbose: true
