apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observer-rolebinding
subjects:
  - kind: ServiceAccount
    name: observer-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: observer-cluster-role
  apiGroup: rbac.authorization.k8s.io
