apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observer-cluster-role
rules:
  - apiGroups: [""]
    resources:
      ["pods", "pods/log", "pods/status", "deployments", "jobs", "cronjobs"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
