apiVersion: v1
kind: Service
metadata:
  name: flock-observer
spec:
  type: NodePort
  selector:
    app: flock-observer
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30206
