# yaml-language-server: $schema=../../json_schemas/main/LLMTool.json
---
apiVersion: flock/v1
kind: LLMTool
namespace: default
metadata:
  name: my-llm-tool
  description: "Useful for coming up with todo lists. Input: an objective to create a todo list for. Output: a todo list for that objective. Please be very clear what the objective is!"
  labels:
    app: my_app
spec:
  vendor: LLMChain
  options:
    verbose: true
  dependencies:
    - kind: PromptTemplate
      name: my-prompt-template
      namespace: default
    - kind: LLMChat
      name: my-openai-llm
      namespace: default
