# yaml-language-server: $schema=../../json_schemas/main/LoadTool.json
---
apiVersion: flock/v1
kind: LoadTool
namespace: default
metadata:
  name: google-search-gpt-4
  description: Reliable source for current events and facts beyond 2021.
  labels:
    app: my_app
spec:
  vendor: serpapi
  options:
    verbose: true
  dependencies:
    - kind: LLMChat
      name: openai-gpt-4
      namespace: default
