# yaml-language-server: $schema=../../../json_schemas/main/LoadToolSchema.json
---
apiVersion: flock/v1
kind: LoadTool
namespace: default
metadata:
  name: my-wolfram-alpha
  description: Data computation, factual information retrieval, mathematics problems, scientific queries, and statistics.
  labels:
    app: my_app
spec:
  vendor: wolfram-alpha
  options:
    verbose: true
  dependencies:
    - kind: LLMChat
      name: my-openai-llm
      namespace: default
