# yaml-language-server: $schema=../../json_schemas/main/LoadTool.json
---
apiVersion: flock/v1
kind: LoadTool
namespace: default
metadata:
  name: wolfram-alpha
  description: Data computation, factual information retrieval, mathematics problems, scientific queries, and statistics.
  labels:
    app: my_app
spec:
  vendor: wolfram-alpha
  options:
    verbose: true
  dependencies:
    - kind: LLMChat
      name: openai-gpt-3-5
      namespace: default
