# yaml-language-server: $schema=../../json_schemas/main/LLMSchema.json
---
apiVersion: flock/v1
kind: LLM
namespace: default
metadata:
  name: my-gpt4all-llm
  description: openai language model
  labels:
    app: my_app
spec:
  vendor: GPT4All
  options:
    model: /Users/adamyodinsky/.flock/models/ggml-gpt4all-l13b-snoozy.bin
