# yaml-language-server: $schema=../../json_schemas/main/DeploymentSchema.json
---
apiVersion: flock/v1
kind: FlockDeployment
namespace: default
category: deployment
metadata:
  name: my-agent-deployment
  description: A Q&A chat agent server
  labels:
    app: my_app
spec:
  container:
    image_pull_policy: IfNotPresent
    image: flock-agent
    ports:
      - name: http
        container_port: 8000
        protocol: TCP
    env:
      MONGO_USERNAME: root
      MONGO_PASSWORD: password
      MONGO_HOST: 192.168.1.162
      OPENAI_API_KEY: "<key>"
      SERPAPI_API_KEY: "<key>"
  targetResource:
    kind: Agent # this is an agent resource manifest reference that should be loaded to the Flock-Agent FastAPI app.
    name: my-agent
    namespace: default
    labels:
      app: my_app
    options: # this is a dict of options that will be passed to the Flock-Agent FastAPI app. deployer can use this to override the options in the target's manifest
      verbose: true
