version: '3.9'

# source: https://penkovski.com/post/vault-dev-server-docker-compose

services:
  vault:
      hostname: vault
      container_name: vault
      image: vault
      environment:
        VAULT_ADDR: "http://0.0.0.0:8200"
        VAULT_API_ADDR: "http://0.0.0.0:8200"
      ports:
        - "8200:8200"
      volumes:
        - ./volumes/vault/file:/vault/file:rw
      cap_add:
        - IPC_LOCK
      entrypoint: vault server -dev -dev-listen-address="0.0.0.0:8200" -dev-root-token-id="root"

  vault-init:
    container_name: vault-init
    image: vault
    volumes:
      - ./vault-init.sh:/vault-init.sh
    depends_on:
      - vault
    restart: "no"
    entrypoint: sh -c "/vault_init.sh"